version: '3.8'
services:
  db_test:
    container_name: mysql_test
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ot
    ports:
      - 7777:3306
    volumes:
      - ./database/migration:/docker-entrypoint-initdb.d
    networks:
      - tibia_backend_test
    logging:
      driver: none
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-prootpassword", "-e", "DESCRIBE ot.accounts"]
      start_period: 30s
      interval: 1s
      timeout: 1s
      retries: 30
  
  api:
    container_name: tibia-backend
    build: .
    restart: on-failure
    depends_on:
      db_test:
        condition: service_healthy
    environment:
      DB_NAME: ot
      DB_HOST: db_test
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: rootpassword
      JWT_KEY: adAm03lpaLa03Gmz1KazA02L1K5K34J20amcA20
    networks:
      - tibia_backend_test
    logging:
      driver: none
    healthcheck:
        test: ["CMD", "curl" ,"-f", "localhost:7474/api/health"]
        start_period: 1s
        interval: 1s
        timeout: 1s
        retries: 15
  
  test:
    container_name: test
    build: ./tests
    depends_on:
      db_test:
        condition: service_started
      api:
        condition: service_healthy
    environment:
      DB_NAME: ot
      DB_HOST: db_test
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: rootpassword
      JWT_KEY: adAm03lpaLa03Gmz1KazA02L1K5K34J20amcA20
    tty: true
    networks:
      - tibia_backend_test
networks:
  tibia_backend_test: