version: '3.1'
services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "$DB_PASSWORD"
      MYSQL_DATABASE: "$DB_NAME"
      MYSQL_USER: "$DB_USER"
      MYSQL_PASSWORD: "$DB_PASSWORD"
    ports:
      - $DB_PORT:3306
    volumes:
      - ./database/migration:/docker-entrypoint-initdb.d
    networks:
      - tibia_backend
  api:
    container_name: tibia-backend
    build: .
    restart: on-failure
    environment:
      DB_NAME: "$DB_NAME"
      DB_HOST: mysql
      DB_PORT: "$DB_PORT"
      DB_USER: root
      DB_PASSWORD: "$DB_PASSWORD"
      JWT_KEY: "$JWT_KEY"
    ports:
      - 7474:7474
    networks:
      - tibia_backend
networks:
  tibia_backend: